<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>ReCoPa</RootNamespace>
        <AssemblyVersion>2.0.0</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <None Include="assets\app-icon.ico" CopyToOutputDirectory="PreserveNewest" />
        <None Include="assets\app-icon.icns" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    
    <PropertyGroup>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Avalonia.ReactiveUI" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
        <PackageReference Include="Material.Icons.Avalonia" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="ReactiveUI" />
        <PackageReference Include="ReactiveUI.Avalonia" />
        <PackageReference Include="ReactiveUI.Fody" />
        <PackageReference Include="SukiUI" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ReCoPa.Plugins\ReCoPa.Plugins.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\" />
    </ItemGroup>

    <ItemGroup>
        <Watch Include="**\*.axaml" />
        <Watch Include="**\*.xaml" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\VisualizationContainerView.axaml.cs">
        <DependentUpon>VisualizationContainerView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\SessionView.axaml.cs">
        <DependentUpon>SessionView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\EndpointsDialogView.axaml.cs">
        <DependentUpon>EndpointsDialogView.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Views\Visualizations\PulseMonitorView.axaml" />
    </ItemGroup>
</Project>
